<p style="text-align:center">
    <a href="https://skills.network" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="350" alt="Skills Network Logo">
    </a>
</p>

# **Hands-on Lab : Web Scraping**

Estimated time needed: **30 to 45** minutes

## Objectives

In this lab you will perform the following:

-   Extract information from a given web site
-   Write the scraped data into a csv file.

## Extract information from the given web site

You will extract the data from the below web site: <br>

In [3]:
#this url contains the data you need to scrape
url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DA0321EN-SkillsNetwork/labs/datasets/Programming_Languages.html"

The data you need to scrape is the **name of the programming language** and **average annual salary**.<br> It is a good idea to open the url in your web broswer and study the contents of the web page before you start to scrape.

Import the required libraries

In [4]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

Download the webpage at the url

In [5]:
data = requests.get("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DA0321EN-SkillsNetwork/labs/datasets/Programming_Languages.html").text

Create a soup object

In [6]:
soup = BeautifulSoup(data, 'html.parser')

Scrape the `Language name`, `Created By` `annual average salary`and `Learning Difficulty`.

In [7]:
#your code goes here
from bs4 import BeautifulSoup
import requests
import pandas as pd

table = soup.find('table')
data_list = []

# Loop through each row in the table
for row in table.find_all('tr'):
    cols = row.find_all('td')
    # Skip the header row if necessary
    if cols[1].getText() == 'Language':
        continue

    Language_name = cols[1].getText()
    Created_by = cols[2].getText()
    Annual_average_salary = cols[3].getText()
    Learning_Difficulty = cols[4].getText()

    print('Language name= {}, Created By = {}, Annual average salary= {} and Learning Difficulty = {}'.format(Language_name, Created_by, Annual_average_salary, Learning_Difficulty))

    data_list.append({
        'Language name': Language_name,
        'Created By': Created_by,
        'annual average salary': Annual_average_salary,
        'Learning Difficulty': Learning_Difficulty
    })

table_df = pd.DataFrame(data_list, columns=['Language name', 'Created By', 'annual average salary', 'Learning Difficulty'])
table_df

Language name= Python, Created By = Guido van Rossum, Annual average salary= $114,383 and Learning Difficulty = Easy
Language name= Java, Created By = James Gosling, Annual average salary= $101,013 and Learning Difficulty = Easy
Language name= R, Created By = Robert Gentleman, Ross Ihaka, Annual average salary= $92,037 and Learning Difficulty = Hard
Language name= Javascript, Created By = Netscape, Annual average salary= $110,981 and Learning Difficulty = Easy
Language name= Swift, Created By = Apple, Annual average salary= $130,801 and Learning Difficulty = Easy
Language name= C++, Created By = Bjarne Stroustrup, Annual average salary= $113,865 and Learning Difficulty = Hard
Language name= C#, Created By = Microsoft, Annual average salary= $88,726 and Learning Difficulty = Hard
Language name= PHP, Created By = Rasmus Lerdorf, Annual average salary= $84,727 and Learning Difficulty = Easy
Language name= SQL, Created By = Donald D. Chamberlin, Raymond F. Boyce., Annual average salary= $84,793 and Learning Difficulty = Easy
Language name= Go, Created By = Robert Griesemer, Ken Thompson, Rob Pike., Annual average salary= $94,082 and Learning Difficulty = Difficult

,Language name,Created By,annual average salary,Learning Difficulty
0,Python,Guido van Rossum,"$114,383",Easy
1,Java,James Gosling,"$101,013",Easy
2,R,"Robert Gentleman, Ross Ihaka","$92,037",Hard
3,Javascript,Netscape,"$110,981",Easy
4,Swift,Apple,"$130,801",Easy
5,C++,Bjarne Stroustrup,"$113,865",Hard
6,C#,Microsoft,"$88,726",Hard
7,PHP,Rasmus Lerdorf,"$84,727",Easy
8,SQL,"Donald D. Chamberlin, Raymond F. Boyce.","$84,793",Easy
9,Go,"Robert Griesemer, Ken Thompson, Rob Pike.","$94,082",Difficult

Create a _dataframe_ for scrapped data

In [10]:
import pandas as pd
# We can define df using table_df from the scraping step
try:
    df = table_df.copy()
except NameError:
    df = pd.DataFrame(data_list)
display(df)

,Language name,Created By,annual average salary,Learning Difficulty
0,Python,Guido van Rossum,"$114,383",Easy
1,Java,James Gosling,"$101,013",Easy
2,R,"Robert Gentleman, Ross Ihaka","$92,037",Hard
3,Javascript,Netscape,"$110,981",Easy
4,Swift,Apple,"$130,801",Easy
5,C++,Bjarne Stroustrup,"$113,865",Hard
6,C#,Microsoft,"$88,726",Hard
7,PHP,Rasmus Lerdorf,"$84,727",Easy
8,SQL,"Donald D. Chamberlin, Raymond F. Boyce.","$84,793",Easy
9,Go,"Robert Griesemer, Ken Thompson, Rob Pike.","$94,082",Difficult

Save the scrapped data into a file named _popular-languages.csv_

In [11]:
df.to_csv('popular-languages.csv', index=False)
print("Saved successfully to popular-languages.csv")

Saved successfully to popular-languages.csv

### Download the CSV file to your local computer
Run the cell below to prompt your browser to download `popular-languages.csv` directly.

In [12]:
from google.colab import files

files.download('popular-languages.csv')

## Authors

Ramesh Sannareddy

### Other Contributors

Rav Ahuja

 Copyright © 2020 IBM Corporation. This notebook and its source code are released under the terms of the [MIT License](https://cognitiveclass.ai/mit-license?cm_mmc=Email_Newsletter-_-Developer_Ed%2BTech-_-WW_WW-_-SkillsNetwork-Courses-IBM-DA0321EN-SkillsNetwork-21426264&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ&cm_mmc=Email_Newsletter-_-Developer_Ed%2BTech-_-WW_WW-_-SkillsNetwork-Courses-IBM-DA0321EN-SkillsNetwork-21426264&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ&cm_mmc=Email_Newsletter-_-Developer_Ed%2BTech-_-WW_WW-_-SkillsNetwork-Courses-IBM-DA0321EN-SkillsNetwork-21426264&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ&cm_mmc=Email_Newsletter-_-Developer_Ed%2BTech-_-WW_WW-_-SkillsNetwork-Courses-IBM-DA0321EN-SkillsNetwork-21426264&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ).

<!--## Change Log

<!--| Date (YYYY-MM-DD) | Version | Changed By        | Change Description                 |
| ----------------- | ------- | ----------------- | ---------------------------------- |
| 2020-10-17        | 0.1     | Ramesh Sannareddy | Created initial version of the lab |--!>